server:
  port: 8082
  servlet:
    context-path: /tech-challenge-customer/
spring:
  application:
    name: tech-challenge-customer
  datasource:
    url: >-
      jdbc:mysql://${DB_SERVER}/${DB_NAME}?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
swagger:
  title: Api Costumer
  version: 1.0
  description: APi para cadastro e pesquisa de Clientes
  contact:
    name: Daniel A. Correa
    email: daniel.cor@outlook.com

kafka:
  topic:
    consumer:
      error:
        payment: tech.error.payment
        groupId: customer-payment
