server:
  port: 8085
spring:
  application:
    name: tech-challenge-customer
  datasource:
    url: >-
      jdbc:mysql://localhost:3306/customer?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dani
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
swagger:
  title: Api Costumer
  version: 1.0
  description: APi para cadastro e pesquisa de Clientes
  contact:
    name: Daniel A. Correa
    email: daniel.cor@outlook.com

kafka:
  topic:
    consumer:
      error:
        payment: tech.error.payment
        groupId: orders
