apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30005