apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-customer
  labels:
    app: tech-challenge-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-customer
  template:
    metadata:
      labels:
        app: tech-challenge-customer
    spec:
      containers:
      - name: tech-challenge-customer
        image: daniel36/tech-challenge-customer:02
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8085
        resources:
          limits:
            cpu: 0.2
            memory: "512Mi"
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mongo-host

        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mongo-username

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---
