apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-customer
  labels:
    app: tech-challenge-customer
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-customer
  ports:
    - protocol: TCP
      name: http
      port: 8085
      targetPort: 8085
      nodePort: 30005